name: flutter_quran_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  http: 0.13.4
  lottie: 1.3.0
  google_fonts: 2.3.1
  shimmer: 2.0.0
  loading_animation_widget: 1.1.0+3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true

